name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-with-make-cmake:
    name: Build with Make and CMake
    runs-on: ubuntu-latest
    container: libmcu/ci:latest
    steps:
      - name: Clone
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Prepare
        run: |
          git config --system --add safe.directory '*'
      - name: UnitTest
        run: |
          echo "Hello" || true
      - name: Build with Make
        run: |
          make
          make clean
      - name: Build with CMake
        run: |
          cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=projects/arm-none-eabi-gcc.cmake
          cmake --build build
      - name: Process Memory Usage
        id: memseg
        continue-on-error: true
        run: |
          echo "MEMSEG_RESULT_FILE=$(echo .github/memsize.txt)" >> $GITHUB_ENV
          echo "MEMSEG_BASE_FILE=$(echo .github/memsize.baseline)" >> $GITHUB_ENV
          echo "MEMSEG_BASE_TMP=$(echo .github/memsize_tmp.baseline)" >> $GITHUB_ENV

          git checkout main $MEMSEG_BASE_FILE || cp $MEMSEG_BASE_FILE.template $MEMSEG_BASE_FILE
          . $IDF_PATH/export.sh
          arm-none-eabi-size build/*.elf > $MEMSEG_BASE_TMP
          echo -n "\`\`\`\n        " > $MEMSEG_RESULT_FILE
          cat $MEMSEG_BASE_TMP | sed -n 1p >> $MEMSEG_RESULT_FILE
          echo -n "current " >> $MEMSEG_RESULT_FILE
          cat $MEMSEG_BASE_TMP | sed -n 2p >> $MEMSEG_RESULT_FILE
          echo -n "base    " >> $MEMSEG_RESULT_FILE
          cat $MEMSEG_BASE_FILE | sed -n 2p >> $MEMSEG_RESULT_FILE
          echo -n "diff    " >> $MEMSEG_RESULT_FILE
          paste $MEMSEG_BASE_FILE $MEMSEG_BASE_TMP | \
            sed -n 2p | \
            awk '{printf "%7d %7d %7d", $7-$1, $8-$2, $9-$3}' >> $MEMSEG_RESULT_FILE
          echo "\n\`\`\`" >> $MEMSEG_RESULT_FILE
          cp $MEMSEG_BASE_TMP $MEMSEG_BASE_FILE
          echo "MEMSEG_BASE=$(cat $MEMSEG_BASE_FILE)" >> $GITHUB_ENV
          echo "MEMSEG_RESULT=$(cat $MEMSEG_RESULT_FILE)" >> $GITHUB_ENV
      - name: Comment Memory Size
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require("fs");
            const filepath = "${{ steps.memseg.outputs.MEMSEG_RESULT }}";
            const body = fs.readFileSync(filepath, "utf-8");
            github.rest.issues.createComment({
              issue_number: ${{ github.event.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })
      - name: Static Analysis
        id: analysis
        run: |
          echo "CODECHECKER_RESULT_FILE=$(echo .github/codechecker_result.txt)" >> $GITHUB_ENV
          echo "CODECHECKER_BASE_FILE=$(echo .github/codechecker.baseline)" >> $GITHUB_ENV
          echo "CODECHECKER_BASE_TMP=$(echo .github/codechecker_tmp.baseline)" >> $GITHUB_ENV

          sed -i 's/-fno-tree-switch-conversion//g' build/compile_commands.json
          sed -i 's/-fstrict-volatile-bitfields//g' build/compile_commands.json
          sed -i 's/-std=gnu17//g' build/compile_commands.json
          CodeChecker analyze ./build/compile_commands.json --enable sensitive \
            --output ./reports --ignore .codechecker.exclude
          git checkout main $CODECHECKER_BASE_FILE || true
          CodeChecker parse ./reports -e baseline -o $CODECHECKER_BASE_TMP || true
          CodeChecker cmd diff -b $CODECHECKER_BASE_FILE \
            -n ./reports --new > $CODECHECKER_RESULT_FILE ||
            CodeChecker parse reports > $CODECHECKER_RESULT_FILE
          echo "CODECHECKER_RESULT=$(cat $CODECHECKER_RESULT_FILE)" >> $GITHUB_ENV
          echo "CODECHECKER_BASE=$(cat $CODECHECKER_BASE_FILE)" >> $GITHUB_ENV
      - name: Process Analysis Result
        if: always()
        run: |
          sed -i '1s/^/```\n/' ${{ steps.analysis.outputs.CODECHECKER_RESULT }}
          echo "\n\`\`\`" >> %{{ steps.analysis.outputs.CODECHECKER_RESULT }}
          cp ${{ steps.analysis.outputs.CODECHECKER_BASE_TMP }} ${{ steps.analysis.outputs.CODECHECKER_BASE }}
      - name: Comment Static Analysis Result
        if: always() && github.event_name == 'pull_request' && steps.analysis.outcome != 'success'
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require("fs");
            const filepath = "${{ steps.analysis.outputs.CODECHECKER_RESULT }}";
            const body = fs.readFileSync(filepath, "utf-8");
            github.rest.issues.createComment({
              issue_number: ${{ github.event.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })
      - name: Store codechecker baseline
        if: always()
        uses: EndBug/add-and-commit@v9
        with:
          add: '[${{ steps.analysis.outputs.CODECHECKER_BASE }}, ${{ steps.memseg.outputs.MEMSEG_BASE }}]'
          default_author: github_actions
          push: origin HEAD:${{ github.head_ref }} --force
